language: python
python: 3.7
os:
  - linux
  - osx
  - windows

before_script:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install python2 python3; fi

script:
  - ./cryptor.py test test test
  - ./main.py
